# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Persimmon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'TLPhotoPicker'
  pod 'Toast-Swift', '~> 5.0.0’

  # Pods for Persimmon

end
